name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-tests:
    uses:
      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    strategy:
      matrix:
        include:
          - charm: "falco"
            provider: "lxd"
            provider-channel: "6/stable"
          - charm: "falcosidekick-k8s"
            provider: "k8s"
            provider-channel: "1.34-classic/stable"
    with:
      load-test-enabled: false
      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
      trivy-fs-enabled: true
      trivy-image-config: "trivy.yaml"
      self-hosted-runner: true
      juju-channel: "3/stable"
      channel: "${{ matrix.provider-channel }}"
      with-uv: true
      use-canonical-k8s: true
      provider: "${{ matrix.provider }}"
      identifier: "${{ matrix.charm }}"
      working-directory: "${{ matrix.charm }}-operator"
  allure-report:
    if: ${{ !cancelled() && github.event_name == 'schedule' }}
    needs:
    - integration-tests
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
