name: Promote charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - "[\"falco\",\"0.42/edge\"]"
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - "[\"falco\",\"0.42/stable\"]"
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    outputs:
      origin-channel: ${{ steps.parse-option.outputs.origin-channel }}
      destination-channel: ${{ steps.parse-option.outputs.destination-channel }}
    steps:
      - name: Parse option
        id: parse-option
        run: |
          echo "input-channel=${{ fromJson(github.event.inputs.origin-channel) }}" >> $GITHUB_OUTPUT
          echo "destination-channel=${{ fromJson(github.event.inputs.destination-channel) }}" >> $GITHUB_OUTPUT

  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    needs: parse-inputs
    with:
      origin-channel: "${{ needs.parse-inputs.outputs.origin-channel[1] }}"
      destination-channel: "${{ needs.parse-inputs.outputs.destination-channel[1] }}"
      charm-directory: "${{ needs.parse-inputs.outputs.origin-channel[0] }}-operator"
    secrets: inherit
